#!/bin/bash

mkdir ~/ctf
mkdir ~/ctf/crackmes.one
mkdir ~/ctf/crackmes.one/reallyEasy
mkdir ~/ctf/crackmes.one/reallyEasy/C_Cpp
mkdir ~/ctf/crackmes.one/reallyEasy/Java
mkdir ~/ctf/crackmes.one/reallyEasy/Delphi_Pascal
mkdir ~/ctf/crackmes.one/reallyEasy/ASM
mkdir ~/ctf/crackmes.one/reallyEasy/VisualBasic
mkdir ~/ctf/crackmes.one/reallyEasy/dotNET
mkdir ~/ctf/crackmes.one/reallyEasy/unspecified
mkdir ~/ctf/crackmes.one/easy
mkdir ~/ctf/crackmes.one/easy/C_Cpp
mkdir ~/ctf/crackmes.one/easy/Java
mkdir ~/ctf/crackmes.one/easy/Delphi_Pascal
mkdir ~/ctf/crackmes.one/easy/ASM
mkdir ~/ctf/crackmes.one/easy/VisualBasic
mkdir ~/ctf/crackmes.one/easy/dotNET
mkdir ~/ctf/crackmes.one/easy/unspecified
mkdir ~/ctf/crackmes.one/medium
mkdir ~/ctf/crackmes.one/medium/C_Cpp
mkdir ~/ctf/crackmes.one/medium/Java
mkdir ~/ctf/crackmes.one/medium/Delphi_Pascal
mkdir ~/ctf/crackmes.one/medium/ASM
mkdir ~/ctf/crackmes.one/medium/VisualBasic
mkdir ~/ctf/crackmes.one/medium/dotNET
mkdir ~/ctf/crackmes.one/medium/unspecified
mkdir ~/ctf/pwnable.tw
mkdir ~/ctf/pwnable.tw/100
mkdir ~/ctf/pwnable.tw/150
mkdir ~/ctf/pwnable.tw/200
mkdir ~/ctf/pwnable.kr
mkdir ~/ctf/vmRelatedCTF
mkdir ~/ctf/vmRelatedCTF/pentesterlab
mkdir ~/ctf/vmRelatedCTF/protostar
mkdir ~/ctf/vmRelatedCTF/metasploitableII
mkdir ~/ctf/vmRelatedCTF/metasploitableIII
mkdir ~/ctf/realMalware
mkdir ~/ctf/realMalware/win32
mkdir ~/ctf/realMalware/win32/packed
mkdir ~/ctf/realMalware/win32/ASM
mkdir ~/ctf/realMalware/win32/ASM/packed
mkdir ~/ctf/realMalware/win32/C_Cpp
mkdir ~/ctf/realMalware/win32/C_Cpp/packed
mkdir ~/ctf/realMalware/win32/Java
mkdir ~/ctf/realMalware/win32/Java/packed
mkdir ~/ctf/realMalware/win32/dotNET
mkdir ~/ctf/realMalware/win32/dotNET/packed
mkdir ~/ctf/realMalware/win32/VBasic
mkdir ~/ctf/realMalware/win32/VBasic/packed
mkdir ~/ctf/realMalware/win32/Delphi_Pascal
mkdir ~/ctf/realMalware/win32/Delphi_Pascal/packed
mkdir ~/ctf/realMalware/win64
mkdir ~/ctf/realMalware/win64/packed
mkdir ~/ctf/realMalware/win64/ASM
mkdir ~/ctf/realMalware/win64/ASM/packed
mkdir ~/ctf/realMalware/win64/C_Cpp
mkdir ~/ctf/realMalware/win64/C_Cpp/packed
mkdir ~/ctf/realMalware/win64/Java
mkdir ~/ctf/realMalware/win64/Java/packed
mkdir ~/ctf/realMalware/win64/dotNET
mkdir ~/ctf/realMalware/win64/dotNET/packed
mkdir ~/ctf/realMalware/win64/VBasic
mkdir ~/ctf/realMalware/win64/VBasic/packed
mkdir ~/ctf/realMalware/win64/Delphi_Pascal
mkdir ~/ctf/realMalware/win64/Delphi_Pascal/packed
mkdir ~/ctf/realMalware/www
mkdir ~/ctf/realMalware/www/php
mkdir ~/ctf/realMalware/www/perl
mkdir ~/ctf/root-me/
mkdir ~/ctf/root-me/app-script
mkdir ~/ctf/root-me/app-system
mkdir ~/ctf/root-me/cracking
mkdir ~/ctf/root-me/crypto
mkdir ~/ctf/root-me/forensics
mkdir ~/ctf/root-me/coding
mkdir ~/ctf/root-me/realist
mkdir ~/ctf/root-me/reseaux
mkdir ~/ctf/root-me/stego
mkdir ~/ctf/root-me/web-client
mkdir ~/ctf/root-me/web-server
mkdir ~/ctf/tuts4you/
mkdir ~/ctf/tuts4you/unpackme
mkdir ~/ctf/tuts4you/crackme
mkdir ~/ctf/others

mkdir ~/sourceCode
mkdir ~/sourceCode/gameEngines
mkdir ~/sourceCode/gameEngines/C_Cpp
mkdir ~/sourceCode/gameEngines/java
mkdir ~/sourceCode/gameEngines/python
mkdir ~/sourceCode/malware/
mkdir ~/sourceCode/malware/C_Cpp
mkdir ~/sourceCode/malware/java
mkdir ~/sourceCode/malware/python
mkdir ~/sourceCode/OS
mkdir ~/sourceCode/OS/unix
mkdir ~/sourceCode/OS/nt
mkdir ~/sourceCode/OS/DOS
mkdir ~/sourceCode/OS/others
mkdir ~/sourceCode/antiVirus
mkdir ~/sourceCode/websites
mkdir ~/sourceCode/android
mkdir ~/sourceCode/network
mkdir ~/sourceCode/multimedia
mkdir ~/sourceCode/databases
mkdir ~/sourceCode/compilers
mkdir ~/sourceCode/searchEngines
mkdir ~/sourceCode/blockchaines
mkdir ~/sourceCode/lib
mkdir ~/sourceCode/crypto
mkdir ~/sourceCode/browsers
mkdir ~/sourceCode/P2P
mkdir ~/sourceCode/drones
mkdir ~/sourceCode/AI
mkdir ~/sourceCode/compressors

clear

mkdir ~/dict
mkdir ~/vmware
mkdir ~/vmware/iso
mkdir ~/app
mkdir ~/pgn

clear

mkdir ~/code
mkdir ~/code/c
mkdir ~/code/c/hello
mkdir ~/code/cpp
mkdir ~/code/cpp/hello
mkdir ~/code/www
mkdir ~/code/sh
mkdir ~/code/git
mkdir ~/code/git/mine
mkdir ~/code/git/others
mkdir ~/code/asm
mkdir ~/code/asm/x32
mkdir ~/code/asm/x64
mkdir ~/code/asm/mips
mkdir ~/code/asm/arm32
mkdir ~/code/asm/aarch64
mkdir ~/code/java
mkdir ~/code/java/hello/
mkdir ~/code/kotlin
mkdir ~/code/lua
mkdir ~/code/scheme
mkdir ~/code/sql
mkdir ~/code/py
mkdir ~/code/go
mkdir ~/code/swift

clear

firefox -url "https://www.sourcetrail.com/" "https://mega.nz/sync" "https://www.genymotion.com/download/" "https://github.com/phw/peek" "https://www.freedownloadmanager.org/" "https://www.vmware.com/products/workstation-player/workstation-player-evaluation.html" "https://www.teamviewer.com/en/download/linux/"
